### ISSUE TITLE
Does it work to extract link from fmovies?

### ISSUE THREAD

**Issue by xaiborweb** [pieromarini/fmovies#1]
I am programming a script to do streaming to fmovie.to, but apparently there is a token protection that generates it in the backend and I do not manage to win, I try with slimerjs but it does not work either.

You can do something about it Thank you.

**Comment by pieromarini** [comment]
What exactly do you mean with "do streaming to fmovies.to"?

**Comment by pieromarini** [comment]
This app just scrapes fmovies to get the latest episode of all series you want to keep track of by storing the info on a sqlite db. It uses django as the backend.
